// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAECfrMLyCT1lcwW1DN_ufTKfg3Y5YdR50',
    appId: '1:1070024324129:android:041114dc07445074961f60',
    messagingSenderId: '1070024324129',
    projectId: 'social-app-a466a',
    storageBucket: 'social-app-a466a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIAbt_VvRSyj5ECytctyJ1LZW6z1QkALM',
    appId: '1:1070024324129:ios:447b291410fc369c961f60',
    messagingSenderId: '1070024324129',
    projectId: 'social-app-a466a',
    storageBucket: 'social-app-a466a.appspot.com',
    androidClientId: '1070024324129-dplj4pa7gf9t1ri5cqe3d7v3mivno9f7.apps.googleusercontent.com',
    iosClientId: '1070024324129-3k3ruoci3jnukivbdqaf1o6su8nqsoqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneproject',
  );
}
